version: '3'

services:
  app:
    build: .
    image: slack_ai_chatbot
    container_name: slack_ai_chatbot
    env_file:
      - .env
    volumes:
      - ./:$WORKING_DIR
    working_dir: $WORKING_DIR
    tty: true
